[project]
name = "omoospaceblender"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["omoospace>=0.1.10"]

[dependency-groups]
dev = [
    "bpy==4.2",
    "pip>=25.3",
    "tomlkit>=0.13.3",
]
